### ISSUE TITLE
Add ability to cancel a Stage or Migrate

### ISSUE THREAD

**Issue by jwmatthews** [fusor/mig-controller#87] opened 2019-05-19 14:05 UTC
Assuming that for Stage we want to cancel any running operations.

For Migrate, ideal case would be we cancel any running operations and restore the associated namespaces on source cluster to be in same state as prior to Migrate running.   Essentially we'd want to cancel the running Migrate operations and rollback any changes on source side.

**Comment by dymurray** [comment] 2019-10-21 16:18
Closing as duplicate of https://github.com/fusor/mig-controller/issues/2

**Closed by dymurray** 2019-10-21 16:18 UTC
Labels: enhancement
