### ISSUE TITLE
latest: Stack trace during OCP 3.7 to 4.x migrations

### ISSUE THREAD

**Issue by fbladilo** [fusor/mig-controller#309] opened 2019-09-06 16:38 UTC
The controller is throwing a stack trace while running mssql application migrations from OCP 3.7 to 4.x , the migration actually completes successfully (so it is seemingly harmless) , the issue appears to be around the "EnsureStagePods" phase : 
```
{"level":"info","ts":1567776813.9377446,"logger":"migration|xxvd8","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":""}
{"level":"info","ts":1567776813.9449444,"logger":"migration|nmczc","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"Started"}
{"level":"info","ts":1567776814.041681,"logger":"migration|z54qc","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"Prepare"}
{"level":"info","ts":1567776814.5284986,"logger":"migration|xz8km","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"EnsureInitialBackup"}
{"level":"info","ts":1567776815.824609,"logger":"migration|hrbf5","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"InitialBackupCreated"}
{"level":"info","ts":1567776817.2454302,"logger":"migration|2zp2k","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"InitialBackupCreated"}
W0906 13:33:45.962349       1 reflector.go:270] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: watch of *v1.Restore ended with: etcdserver: mvcc: required revision has been compacted
{"level":"info","ts":1567776826.634754,"logger":"migration|nc9zx","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"InitialBackupCreated"}
{"level":"info","ts":1567776827.4370887,"logger":"migration|7t8lc","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"AnnotateResources"}
{"level":"info","ts":1567776827.5366383,"logger":"migration|7t8lc","msg":"NS annotations/labels added.","name":"mssql-example"}
{"level":"info","ts":1567776827.5466504,"logger":"migration|7t8lc","msg":"PVC annotations/labels added.","ns":"mssql-example","name":"mssql-pvc"}
{"level":"info","ts":1567776827.6208754,"logger":"migration|7t8lc","msg":"Pod annotations/labels added.","ns":"mssql-example","name":"mssql-deployment-1-k9dqk"}
{"level":"info","ts":1567776827.6316893,"logger":"migration|7t8lc","msg":"PV annotations/labels added.","name":"vol47"}
{"level":"info","ts":1567776827.6393068,"logger":"migration|7t8lc","msg":"SA annotations/labels added.","ns":"mssql-example","name":"mssql-example-sa"}
{"level":"info","ts":1567776827.8257334,"logger":"migration|7ljcf","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"EnsureStagePods"}
{"level":"info","ts":1567776828.1208405,"logger":"migration|7ljcf","msg":"Stage pod created.","ns":"mssql-example","name":"mssql-deployment-1-k9dqk-stage"}
{"level":"error","ts":1567776828.127636,"logger":"migration|7ljcf","msg":"","error":"Pod \"mssql-deployment-1-k9dqk\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`, `spec.initContainers[*].image`, `spec.activeDeadlineSeconds` or `spec.tolerations` (only additions to existing tolerations)\n{\"Volumes\":[{\"Name\":\"mssql-vol\",\"HostPath\":null,\"EmptyDir\":null,\"GCEPersistentDisk\":null,\"AWSElasticBlockStore\":null,\"GitRepo\":null,\"Secret\":null,\"NFS\":null,\"ISCSI\":null,\"Glusterfs\":null,\"PersistentVolumeClaim\":{\"ClaimName\":\"mssql-pvc\",\"ReadOnly\":false},\"RBD\":null,\"Quobyte\":null,\"FlexVolume\":null,\"Cinder\":null,\"CephFS\":null,\"Flocker\":null,\"DownwardAPI\":null,\"FC\":null,\"AzureFile\":null,\"ConfigMap\":null,\"VsphereVolume\":null,\"AzureDisk\":null,\"PhotonPersistentDisk\":null,\"Projected\":null,\"PortworxVolume\":null,\"ScaleIO\":null,\"StorageOS\":null},{\"Name\":\"mssql-example-sa-token-w85jj\",\"HostPath\":null,\"EmptyDir\":null,\"GCEPersistentDisk\":null,\"AWSElasticBlockStore\":null,\"GitRepo\":null,\"Secret\":{\"SecretName\":\"mssql-example-sa-token-w85jj\",\"Items\":null,\"DefaultMode\":420,\"Optional\":null},\"NFS\":null,\"ISCSI\":null,\"Glusterfs\":null,\"PersistentVolumeClaim\":null,\"RBD\":null,\"Quobyte\":null,\"FlexVolume\":null,\"Cinder\":null,\"CephFS\":null,\"Flocker\":null,\"DownwardAPI\":null,\"FC\":null,\"AzureFile\":null,\"ConfigMap\":null,\"VsphereVolume\":null,\"AzureDisk\":null,\"PhotonPersistentDisk\":null,\"Projected\":null,\"PortworxVolume\":null,\"ScaleIO\":null,\"StorageOS\":null}],\"InitContainers\":null,\"Containers\":[{\"Name\":\"mssql\",\"Image\":\"quay.io/ocpmigrate/mssql-server:latest\",\"Command\":null,\"Args\":null,\"WorkingDir\":\"\",\"Ports\":[{\"Name\":\"\",\"HostPort\":0,\"ContainerPort\":1433,\"Protocol\":\"TCP\",\"HostIP\":\"\"}],\"EnvFrom\":null,\"Env\":[{\"Name\":\"ACCEPT_EULA\",\"Value\":\"Y\",\"ValueFrom\":null},{\"Name\":\"SA_PASSWORD\",\"Value\":\"\",\"ValueFrom\":{\"FieldRef\":null,\"ResourceFieldRef\":null,\"ConfigMapKeyRef\":null,\"SecretKeyRef\":{\"Name\":\"mssql-secret\",\"Key\":\"mssql-password\",\"Optional\":null}}}],\"Resources\":{\"Limits\":{\"cpu\":\"2\",\"memory\":\"3Gi\"},\"Requests\":{\"cpu\":\"2\",\"memory\":\"3Gi\"}},\"VolumeMounts\":[{\"Name\":\"mssql-vol\",\"ReadOnly\":false,\"MountPath\":\"/var/opt/mssql/data\",\"SubPath\":\"\"},{\"Name\":\"mssql-example-sa-token-w85jj\",\"ReadOnly\":true,\"MountPath\":\"/var/run/secrets/kubernetes.io/serviceaccount\",\"SubPath\":\"\"}],\"LivenessProbe\":null,\"ReadinessProbe\":null,\"Lifecycle\":null,\"TerminationMessagePath\":\"/dev/termination-log\",\"TerminationMessagePolicy\":\"File\",\"ImagePullPolicy\":\"Always\",\"SecurityContext\":{\"Capabilities\":null,\"Privileged\":true,\"SELinuxOptions\":\n\nA: {\"User\":\"\",\"Role\":\"\",\"Type\":\"\",\"Level\":\"s0:c18,c17\"},\"RunAsUser\":null,\"RunAsNonRoot\":null,\"ReadOnlyRootFilesystem\":null},\"Stdin\":false,\"StdinOnce\":false,\"TTY\":false}],\"RestartPolicy\":\"Always\",\"TerminationGracePeriodSeconds\":30,\"ActiveDeadlineSeconds\":null,\"DNSPolicy\":\"ClusterFirst\",\"NodeSelector\":{\"env\":\"users\"},\"ServiceAccountName\":\"mssql-example-sa\",\"AutomountServiceAccountToken\":null,\"NodeName\":\"node1.ci-persistent-37-42-v3-60.internal\",\"SecurityContext\":{\"HostNetwork\":false,\"HostPID\":false,\"HostIPC\":false,\"SELinuxOptions\":{\"User\":\"\",\"Role\":\"\",\"Type\":\"\",\"Level\":\"s0:c18,c17\"},\"RunAsUser\":null,\"RunAsNonRoot\":null,\"SupplementalGroups\":[],\"FSGroup\":1000340000},\"ImagePullSecrets\":[{\"Name\":\"mssql-example-sa-dockercfg-22lvt\"}],\"Hostname\":\"\",\"Subdomain\":\"\",\"Affinity\":null,\"SchedulerName\":\"default-scheduler\",\"Tolerations\":null,\"HostAliases\":null}\n\nB: null,\"RunAsUser\":null,\"RunAsNonRoot\":null,\"ReadOnlyRootFilesystem\":null},\"Stdin\":false,\"StdinOnce\":false,\"TTY\":false}],\"RestartPolicy\":\"Always\",\"TerminationGracePeriodSeconds\":30,\"ActiveDeadlineSeconds\":null,\"DNSPolicy\":\"ClusterFirst\",\"NodeSelector\":{\"env\":\"users\"},\"ServiceAccountName\":\"mssql-example-sa\",\"AutomountServiceAccountToken\":null,\"NodeName\":\"node1.ci-persistent-37-42-v3-60.internal\",\"SecurityContext\":{\"HostNetwork\":false,\"HostPID\":false,\"HostIPC\":false,\"SELinuxOptions\":null,\"RunAsUser\":null,\"RunAsNonRoot\":null,\"SupplementalGroups\":null,\"FSGroup\":null},\"ImagePullSecrets\":[{\"Name\":\"mssql-example-sa-dockercfg-22lvt\"}],\"Hostname\":\"\",\"Subdomain\":\"\",\"Affinity\":null,\"SchedulerName\":\"default-scheduler\",\"Tolerations\":null,\"HostAliases\":null}\n\n","stacktrace":"github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/fusor/mig-controller/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Error\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:59\ngithub.com/fusor/mig-controller/pkg/logging.Logger.Trace\n\t/go/src/github.com/fusor/mig-controller/pkg/logging/logger.go:65\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).ensureStagePodsCreated\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/pod.go:222\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*Task).Run\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/task.go:207\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).migrate\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migrate.go:78\ngithub.com/fusor/mig-controller/pkg/controller/migmigration.(*ReconcileMigMigration).Reconcile\n\t/go/src/github.com/fusor/mig-controller/pkg/controller/migmigration/migmigration_controller.go:190\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/fusor/mig-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1567776828.132674,"logger":"migration|mxxr7","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"EnsureStagePods"}
{"level":"info","ts":1567776828.5306873,"logger":"migration|2468f","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"EnsureStagePods"}
{"level":"info","ts":1567776828.937124,"logger":"migration|wmg6m","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"StagePodsCreated"}
{"level":"info","ts":1567776829.7215421,"logger":"migration|rv7kb","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"StagePodsCreated"}
{"level":"info","ts":1567776830.1251335,"logger":"migration|7t2s7","msg":"Migration [RUN]","name":"mssql-app-mig-1567776675","stage":false,"phase":"RestartRestic"}
```
**To reproduce :** 
1. Deploy OCP 3.7 and 4.x with latest controller 
2. Attempt to migrate https://github.com/fusor/mig-demo-apps/tree/master/apps/mssql-app

**Comment by dymurray** [comment] 2019-10-21 15:26
Closing as duplicate of https://github.com/fusor/mig-controller/issues/266

**Closed by dymurray** 2019-10-21 15:26 UTC
Labels: bug, duplicate
