### ISSUE TITLE
Migration fails and controller is stuck with `Unauthorized` messages

### ISSUE THREAD

**Issue by dymurray** [fusor/mig-controller#217] opened 2019-07-26 18:18 UTC
This was after having the controller up for a a whole day or so. I bounced the pod and things resumed to work.

```
E0726 18:15:03.060415       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Backup: Unauthorized                                                                                                                          
E0726 18:15:03.060452       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.PersistentVolume: Unauthorized                                                                                                                
E0726 18:15:03.060746       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Pod: Unauthorized                                                                                                                             
E0726 18:15:03.060781       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Namespace: Unauthorized                                                                                                                       
E0726 18:15:03.060812       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Secret: Unauthorized                                                                                                                          
E0726 18:15:03.245905       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Secret: Unauthorized                                                                                                                          
E0726 18:15:03.247844       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Namespace: Unauthorized                                                                                                                       
E0726 18:15:03.954521       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Backup: Unauthorized                                                                                                                          
E0726 18:15:04.238510       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.VolumeSnapshotLocation: Unauthorized                                                                                                          
E0726 18:15:04.245044       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.VolumeSnapshotLocation: Unauthorized                                                                                                          
E0726 18:15:04.245912       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.PersistentVolumeClaim: Unauthorized                                                                                                           
E0726 18:15:04.250221       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.PersistentVolumeClaim: Unauthorized                                                                                                           
E0726 18:15:04.251315       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.PersistentVolume: Unauthorized                                                                                                                
E0726 18:15:04.252193       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Pod: Unauthorized                                                                                                                             
E0726 18:15:04.252259       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Restore: Unauthorized                                                                                                                         
E0726 18:15:04.252296       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.BackupStorageLocation: Unauthorized                                                                                                           
E0726 18:15:04.252335       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Restore: Unauthorized                                                                                                                         
E0726 18:15:04.252520       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Backup: Unauthorized                                                                                                                          
E0726 18:15:04.252569       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.BackupStorageLocation: Unauthorized                                                                                                           
E0726 18:15:04.255265       1 reflector.go:134] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:126: Failed to list *v1.Pod: Unauthorized     
```

**Comment by sseago** [comment] 2019-07-29 13:28
I know I get this when running 'make run' either after running for a day or so, or when I start without first running 'oc login'. Seems like it's probably a token/auth timeout issue.

**Comment by alexander-demichev** [comment] 2019-07-29 13:48
I don't have enough background on how controller works, but it looks like your auth token expired. I saw this error while working on CPMA, just renew the token by running `oc login`.

**Comment by jortel** [comment] 2019-08-23 15:44
Agreed.  This is caused by the token expiring.  @dymurray Any objection to closing this?

**Closed** 2019-09-16 19:43 UTC
Labels: GA-blocker, bug
