### ISSUE TITLE
stuck at "StagePodsCreated"

### ISSUE THREAD

**Issue by karimbzu** [fusor/mig-controller#360] opened 2019-11-01 04:27 UTC
Hi,
i am trying to migration mssql-example from okd 3.11 to ocp 4.2.2. However, i stuck during staging processs at "StagePodsCreated". I am using release-v1 for mig operator. Can you please guide me.
Thanks

![image](https://user-images.githubusercontent.com/34478122/68002250-e47fe800-fca2-11e9-8201-7981fd9c8f81.png)

**Comment by jortel** [comment] 2020-01-23 14:21
Duplicate of: https://github.com/fusor/mig-controller/issues/377.
Please reopen if necessary.

**Closed by jortel** 2020-01-23 14:21 UTC
