### ISSUE TITLE
Support migration of apps that will depend on 4.1 images requiring "pull secret"

### ISSUE THREAD

**Issue by djwhatle** [fusor/mig-controller#174] opened 2019-06-24 21:26 UTC
As reported by @garethahealy, mig-controller was unable to migrate a Jenkins app deployed by the Service Catalog in OCP 3.11 onto an OpenShift 4.1 cluster. 

This appears to be an issue with the way that we (or Velero) handles setup of service accounts / dockercfg pull secrets when running a Restore from a Backup, and the lack of a linked OpenShift 4.1 pull secret which is necessary to get the Jenkins and likely other included images on a 4.1 cluster.

Possibly relevant section from Velero source: https://github.com/fusor/velero/blob/fusor-dev/pkg/restore/merge_service_account.go

---
## Reproducer steps

1. On source 3.11 cluster, deploy "nodejs-mongodb-example" from "Pipeline Build Example" in the Service Catalog (Jenkins icon)
1. Create migration to 4.1 cluster
1. Observe Jenkins image not being able to pull image in 4.1 due to:
    1. `Failed to pull image "image-registry.openshift-image-registry.svc:5000/openshift/jenkins@sha256:2600aaa3b380a0be3a2b8c67229209968625d4bfff9579326fd3bee811e951bc": rpc error: code = Unknown desc = Error reading manifest sha256:2600aaa3b380a0be3a2b8c67229209968625d4bfff9579326fd3bee811e951bc in image-registry.openshift-image-registry.svc:5000/openshift/jenkins: unauthorized: authentication required`
1. Create another project and deploy Jenkins on 4.1:
    1. `oc process jenkins-ephemeral -n openshift | oc apply -n anotherproject -f -`
1. Get the Jenkins dockercfg secret from the above, and create it in your migrated project
1. Link it to the Jenkins service account
1. oc secrets link jenkins jenkins-dockercfg --for=pull
1. Delete the Jenkins pod to force a re-pull
1. Watch Jenkins start up correctly in 4.1

**Comment by sseago** [comment] 2019-06-27 18:08
The fix is actually in the plugins.

As it turns out we're dealing with 2 bugs:
1) We need to strip the SHA when restoring the dc -- this was my original suspicion as to what was going on before we hit the pull secret issue. It turns out it is a problem, but the pull secret snagged us before hitting it. 
2) Something is broken with service account restore -- the -dockercfg secret isn't being created. If I run:
oc create namespace pipeline-build-example
oc create serviceaccount -n pipeline-build-example jenkins
before running the migration (with my SHA fix) jenkins runs properly on the destination

The fix for #1 is Fix for this is here: https://github.com/fusor/ocp-velero-plugin/pull/58
For #2, the problem is that the from-backup pull secret reference points to a secret that doesn't exist on the destination cluster, and this non-existent reference is preventing OpenShift from creating a new pull secret and updating the SA. https://github.com/fusor/ocp-velero-plugin/pull/59 adds a serviceaccount plugin which strips these stale pull secret references on restore.

**Comment by dymurray** [comment] 2019-10-21 16:03
@sseago please confirm whether this issue is resolved with the plugin PRs. If it is please close this issue.

**Comment by dymurray** [comment] 2020-02-10 18:59
@sseago Please circle back to this issue and make sure it is okay to close it. If so feel free to do so.

**Comment by sseago** [comment] 2020-02-13 18:42
@dymurray ahh yes, this is done now. Closing.

**Closed by sseago** 2020-02-13 18:42 UTC
Labels: icebox
